name: Run Tests

on:
  push:
    branches:
      - master
      - dev
    tags:
      - v*
env:
  NPROC: 2

jobs:

  # Create Source Distribution and upload artifacts
  python_test:
    runs-on: ${{ matrix.os }}
    name: Python Tests
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'windows-latest']
        python-version: ['3.6', '3.7', '3.8', '3.9' ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.5
        with:
          cmake-version: '3.16.x'

      - name: Install requirements
        run: python -m pip install --upgrade pip setuptools wheel pytest

      - name: Build sdist
        run: |
          python setup.py sdist -d wheelhouse

      - name: Show files
        shell: bash
        run: ls -lh wheelhouse

      - name: Install from sdist
        shell: bash
        run: |
          pip install wheelhouse/*.tar.gz
  
      - name: Run Tests
        run: |
          pytest
