name: Wheels

on:
  push:
    branches:
      - master
      - dev
env:
  NPROC: 2

jobs:

  # Create Source Distribution and upload artifacts
  build_sdist:
    name: Source distribution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.4

      - name: Install requirements
        run: pip install --user twine

      - name: Build sdist
        run: |
          python setup.py sdist -d wheelhouse

      - name: Install from sdist
        run: |
          pip install --user wheelhouse/*.tar.gz
  
      - name: Check sdist
        run: |
          python -m twine check wheelhouse/*

      - name: Upload sdist
        uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: wheelhouse/*.tar.gz

    # Create Binary Distribution (wheels) and upload artifacts
  build_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            cibw-arch: manylinux_x86_64
          - os: windows-latest
            cibw-arch: win_amd64
          # - os: macos-latest
          #   cibw-arch: macosx_x86_64
          # - os: ubuntu-latest
          #   cibw-arch: manylinux_i686
          # - os: windows-latest
          #   cibw-arch: win32
          #   python-arch: x86
          #   cmake-arch: -A Win32
    env:
      CIBW_SKIP: "cp27-* cp35-* cp27-* pp27-* pp36-* pp37-*"
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Set up Python version
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.4

      - name: Install requirements
        run: |
          python -m pip install cibuildwheel twine

      - name: Configure cibuildwheel
        shell: bash
        run: |
          echo "CIBW_BUILD=*-${{ matrix.cibw-arch }}" >> $GITHUB_ENV
          echo "CIBW_BEFORE_ALL_LINUX=pip install cmake && ln -s \$(which cmake) /usr/local/bin/cmake" >> $GITHUB_ENV

      - name: Build Wheels
        run: |
          python -m cibuildwheel --output-dir wheelhouse

      - name: Show files
        shell: bash
        run: ls -lh wheelhouse

      - name: Upload wheels
        uses: actions/upload-artifact@v2
        with:
          path: wheelhouse/*.whl
          name: wheels

  upload_wheels:
    runs-on: ubuntu-latest
    needs: [build_sdist, build_wheels]

    steps:
      - name: Collect sdist and wheels
        uses: actions/download-artifact@v2
        with:
          name: wheels
          path: wheelhouse     
    
      # Upload to testing pypi
      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.test_pypi_password }}
          packages_dir: wheelhouse/
          repository_url: https://test.pypi.org/legacy/

      # Publish to official pypi channel
      - name: Publish package
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
          packages_dir: wheelhouse/

